import { getErrorMessage } from "@lichens-innovation/ts-common";
import { logger } from "@lichens-innovation/ts-common/logger";
import { readFileSync, writeFileSync } from "node:fs";
import { createInterface } from "node:readline";

const packageJsonPath = "./package.json";
const constantsFilename = "./src/version.constants.ts";

interface PackageMetadata {
  name: string;
  description: string;
  version: string;
  author: string;
  repository: string;
  [key: string]: unknown;
}

const readPackageJson = (): PackageMetadata => {
  const content = readFileSync(packageJsonPath, { encoding: "utf8" });
  try {
    return JSON.parse(content) as PackageMetadata;
  } catch (error: unknown) {
    logger.error("[generate-version] Failed to parse package.json", { error });
    throw error;
  }
};

const writePackageJson = (packageData: PackageMetadata): void => {
  writeFileSync(packageJsonPath, JSON.stringify(packageData, null, 2) + "\n", {
    encoding: "utf8",
  });
};

const promptVersion = (currentVersion: string): Promise<string> => {
  const question = `\t- Current version: ${currentVersion}\n\t- New version (press Enter to keep current): `;

  return new Promise((resolve) => {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    rl.question(question, (answer) => {
      rl.close();
      const newVersion = answer.trim();
      resolve(newVersion || currentVersion);
    });
  });
};

const generateConstantsFile = (packageMetadata: PackageMetadata): string => {
  const { name, description, version, author, repository } = packageMetadata;
  const dateIso = new Date().toISOString();
  const dateOnly = dateIso.split("T")[0];

  return `/** habit-hooks-disable non-essential-comment
 * ----------------------------------------------------------------------------------------
 * Do not edit this file, it is auto-generated by scripts/generate-version.ts
 * ----------------------------------------------------------------------------------------
 */
export const APP_VERSION_INFO = Object.freeze({
  NAME: "${name}",
  DESCRIPTION: "${description}",
  REPOSITORY: "${repository}",
  AUTHOR: "${author}",
  VERSION: "${version}",
  VERSION_DATE: "${dateOnly}",
  VERSION_DATE_ISO: "${dateIso}",
});
`;
};

const writeConstantsFile = (packageMetadata: PackageMetadata): void => {
  const data = generateConstantsFile(packageMetadata);
  logger.info(`[generate-version] Writing file "${constantsFilename}"`, { version: packageMetadata.version });
  writeFileSync(constantsFilename, data, { encoding: "utf8" });
  logger.info(`[generate-version] File "${constantsFilename}" written successfully`);
};

interface CreateUpdatedPackageMetadataArgs {
  packageMetadata: PackageMetadata;
  newVersion: string;
}

const createUpdatedPackageMetadata = ({
  packageMetadata,
  newVersion,
}: CreateUpdatedPackageMetadataArgs): PackageMetadata => {
  const newPackageMetadata = { ...packageMetadata, version: newVersion };
  logger.info(`[generate-version] Updating package.json with version "${newVersion}"`);
  writePackageJson(newPackageMetadata);
  logger.info("[generate-version] package.json updated successfully");

  return newPackageMetadata;
};

const isSyncMode = (): boolean => {
  return process.argv.includes("--sync") || process.env.CI === "true" || !process.stdin.isTTY;
};

const main = async (): Promise<void> => {
  logger.info("[generate-version] Version generator script");

  const packageMetadata = readPackageJson();

  if (isSyncMode()) {
    logger.info("[generate-version] Sync mode — writing constants from package.json", {
      version: packageMetadata.version,
    });
    writeConstantsFile(packageMetadata);
    return;
  }

  const currentVersion = packageMetadata.version;
  const newVersion = await promptVersion(currentVersion);

  let updatedMetadata = packageMetadata;
  if (newVersion !== currentVersion) {
    updatedMetadata = createUpdatedPackageMetadata({ packageMetadata, newVersion });
  } else {
    logger.info("[generate-version] Version unchanged", { version: currentVersion });
  }

  writeConstantsFile(updatedMetadata);
};

main().catch((err: unknown) => {
  const message = getErrorMessage(err);
  logger.error(`[generate-version] Error: ${message}`, { err });
  process.exit(1);
});
