/* eslint-disable */
// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.js
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: 'web-toolbox',
  DESCRIPTION: "Collection of web developer utilities packaged as a desktop app",
  VERSION: '2.9.0',
  VERSION_DATE: '2024-07-01',
});

export const LONG_VERSION_DATE = '2.9.0 (2024-07-01)';
