/* eslint-disable */
// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.js
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: 'web-toolbox',
  DESCRIPTION: "Collection of web developer utilities",
  VERSION: '2.10.0',
  VERSION_DATE: '2025-01-18',
});

export const LONG_VERSION_DATE = '2.10.0 (2025-01-18)';
