// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.js
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: "web-toolbox",
  DESCRIPTION: "Collection of web development utilities. Like a Swiss knife for web developers.",
  REPOSITORY: "https://github.com/amwebexpert/etoolbox",
  AUTHOR: "amwebexpert@gmail.com",
  VERSION: "4.1.0",
  VERSION_DATE: "2026-01-10",
  VERSION_DATE_ISO: "2026-01-10T11:45:08.963Z",
});

export const LONG_VERSION_DATE = "4.1.0 (2026-01-10)";
