// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.js
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: "web-toolbox",
  DESCRIPTION: "Collection of web development utilities. Like a Swiss knife for web developers.",
  REPOSITORY: "https://github.com/amwebexpert/etoolbox",
  AUTHOR: "amwebexpert@gmail.com",
  VERSION: "4.6.1",
  VERSION_DATE: "2026-06-09",
  VERSION_DATE_ISO: "2026-06-09T13:01:44.529Z",
});

export const LONG_VERSION_DATE = "4.6.1 (2026-06-09)";
