// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.js
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: "web-toolbox",
  DESCRIPTION: "Collection of web development utilities. Like a Swiss knife for web developers.",
  REPOSITORY: "https://github.com/amwebexpert/etoolbox",
  AUTHOR: "amwebexpert@gmail.com",
  VERSION: "4.5.0",
  VERSION_DATE: "2026-05-17",
  VERSION_DATE_ISO: "2026-05-17T13:28:37.772Z",
});

export const LONG_VERSION_DATE = "4.5.0 (2026-05-17)";
