/** habit-hooks-disable non-essential-comment
 * ----------------------------------------------------------------------------------------
 * Do not edit this file, it is auto-generated by scripts/generate-version.ts
 * ----------------------------------------------------------------------------------------
 */
export const APP_VERSION_INFO = Object.freeze({
  NAME: "web-toolbox",
  DESCRIPTION: "Collection of web development utilities. Like a Swiss knife for web developers.",
  REPOSITORY: "https://github.com/amwebexpert/etoolbox",
  AUTHOR: "amwebexpert@gmail.com",
  VERSION: "4.8.0",
  VERSION_DATE: "2026-09-05",
  VERSION_DATE_ISO: "2026-09-05T20:43:25.342Z",
});
