#!/usr/bin/env sh
echo "________________________________________________________"
echo "Running commitlint to ensure the commit message is valid…"
bunx --no-install commitlint --edit "$1"
echo "✅ Commitlint completed"
